### ISSUE TITLE
Why decomposing password-store-otp-insert into 2 functions

### ISSUE THREAD

**Issue by DamienCassou** [volrath/password-store-otp.el#2]
Why do you decompose functions like this:

```emacs
(defun password-store-otp-insert (entry otp-uri)
  "Insert a new ENTRY containing OTP-URI."
  (interactive (list (read-string "Password entry: ")
                     (read-passwd "OTP URI: " t)))
  (password-store-otp--insert entry otp-uri))
```

This seems to defeat the purpose of `interactive`. Can't you merge `password-store-otp-insert` and `password-store-otp--insert` into just 1 function?

**Comment by volrath** [comment]
@DamienCassou Because `password-store-otp-insert` and `password-store-otp--insert` work in different ways, besides one being interactive and the other one not.

`password-store-otp--insert` is the abstraction of the command to be used to insert *or* append a URI to the store, that's why it has a third optional parameter `append`, and it's used by the interactive command `password-store-otp-append`.

The main source of the confusion may be the verb "insert" used in both functions. I want to keep "insert" for the interactive command, to reflect `pass-otp`'s insert bash command, but for the internal "insert" I'm open to any other suggestion.

**Comment by DamienCassou** [comment]
> The main source of the confusion may be the verb "insert" used in both functions

I guess that didn't help :-)

> for the internal "--insert" I'm open to any other suggestion.
 
I don't think it matters that much.

You may close the issue.
